FROM  python:2.7

RUN apt-get update && apt-get -y install python-pip
ADD requirements.txt .
RUN pip install -r requirements.txt
ADD render.py .
COPY templates/ templates/
VOLUME /config
CMD echo "starting... "; rm -f config.yml ;\
  rm -rf target ;\
  curl $TEMPURL > config.yml && \
  python -u render.py && \
  tar -C target -cvzf /config/config.tar.gz . ;\
  echo "finished run" ; sleep 600
