FROM  azulinho/ci-platform.stage1:master

ARG DEB_URL

RUN curl -sL "$DEB_URL" \
    > /tmp/jenkins.deb && \
    dpkg -i /tmp/jenkins.deb && \
    rm -f /tmp/jenkins.deb && \
    rm -rf /var/lib/jenkins

ADD requirements.txt .
ADD render.py /render.py
COPY templates/ /templates/
RUN pip install -r requirements.txt

ADD bootstrap.sh /
RUN chmod 755 /bootstrap.sh


VOLUME /config
VOLUME /var/lib/jenkins

CMD /bootstrap.sh
